### model
model_name_or_path: /H1/zhouhongli/JudgePO/models/Llama-3-8B-Instruct

### method
stage: sft
do_train: true
finetuning_type: full

### dataset
dataset_dir: train/LLaMA-Factory/data
dataset: helpsteer_sft
template: llama3
cutoff_len: 1024
max_samples: 100000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /H1/zhouhongli/JudgePO/LLaMA-Factory/output/Llama-3-8B-Instruct-helpsteer_sft_lr_1e-6
logging_steps: 1
save_steps: 1000
overwrite_output_dir: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 16
learning_rate: 1.0e-6
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.003
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: 'no'
eval_steps: 500
