### model
model_name_or_path: /H1/zhouhongli/JudgePO/models/Llama-2-13B-chat
### method
stage: dpo
do_train: true
finetuning_type: full
pref_beta: 0.1
# simpo_gamma: 0.3
pref_loss: orpo  # choices: [sigmoid (dpo), orpo, simpo]

### dataset
dataset_dir: train/LLaMA-Factory/data
dataset: offsetbias_dpo
template: llama2
cutoff_len: 1024
max_samples: 1000000
overwrite_cache: true

### output
output_dir: /H1/zhouhongli/JudgePO/LLaMA-Factory/output/Llama-2-13B-chat-offsetbias_orpo_0.1_lr_2e-5_epoch_3
logging_steps: 1
save_steps: 1000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 16
learning_rate: 2.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0
per_device_eval_batch_size: 1
eval_strategy: "no"
eval_steps: 500
