prompt: llmbar
vllm_args:
  model_args:
    model: ../model/gemma-2b-it
    dtype: float16
    tensor_parallel_size: 1
    trust_remote_code: true
  sampling_params:
    temperature: 0
    max_tokens: 20
hf_args:
  model_args:
    model: google/gemma-2b-it
    dtype: float16
