prompt: llmbar
vllm_args:
  model_args:
    model: ../output/Qwen2.5-3B-Instruct-helpsteer2_et_lr_1e-7
    dtype: float16
    tensor_parallel_size: 1
    trust_remote_code: true
  sampling_params:
    temperature: 0
    max_tokens: 20
hf_args:
  model_args:
    model: Qwen/Qwen2.5-3B-Instruct
    dtype: float16
